<?php /*$this->assets->outputJs() */?>
<script src="js/jquery-3.3.1.js"></script>
<div class="page-header">
    <h1>Congratulations! <?= $module ?></h1>
</div>

<p>You're now flying with Phalcon. Great things are about to happen!</p>

<p>This page is located at <code>views/index/index.phtml</code></p>

<?php foreach ($productList as $v):?>
    <?= $v->name ?><br/>
<?php endforeach;?>

<script type="application/javascript">

    $(function () {
        $('.page-header').append('<p>追加</p>');
    })
</script>
